# Generated by Django 6.0 on 2026-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_dirty'], name='accounts_us_is_dirt_e863a8_idx'),
        ),
    ]
