# Generated by Django 6.0 on 2026-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='residence location'),
        ),
    ]

