# Generated by Django 6.0 on 2026-01-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_add_slugs'),
        ('digitalmenu', '0002_menu'),
        ('inventory', '0011_remove_menuconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menu',
            name='unique_menu_item_per_branch',
        ),
        migrations.RenameIndex(
            model_name='menu',
            new_name='digitalmenu_busines_00fa30_idx',
            old_name='digitalmenu_menu_business_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='menu',
            new_name='digitalmenu_branch__90f20e_idx',
            old_name='digitalmenu_menu_branch_item_idx',
        ),
        migrations.RenameIndex(
            model_name='menuconfig',
            new_name='digitalmenu_busines_301eef_idx',
            old_name='digitalmenu_menuconfig_business_branch_idx',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('branch', 'inventory_item')},
        ),
    ]
