
# Django settings for core project - Tauri Desktop App Configuration

# Generated by 'django-admin startproject' using Django 6.0.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/


import os
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers

try:
    from celery.schedules import crontab  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    crontab = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



def _load_local_env(env_path: Path) -> None:
    """Load environment variables from local .env without overriding existing vars."""
    if not env_path.exists():
        return

    try:
        from dotenv import load_dotenv  # type: ignore
    except Exception:
        for raw_line in env_path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip()
            if key.startswith('export '):
                key = key.replace('export ', '', 1).strip()
            if not key:
                continue
            if (value.startswith('"') and value.endswith('"')) or (
                value.startswith("'") and value.endswith("'")
            ):
                value = value[1:-1]
            os.environ.setdefault(key, value)
        return

    load_dotenv(env_path, override=False)


_load_local_env(BASE_DIR / '.env')


# ============================================
# ENVIRONMENT DETECTION
# ============================================

# Detect if running as desktop app
IS_DESKTOP_APP = os.getenv('NEXT_PUBLIC_APP_ENV') == 'desktop' or os.path.exists(os.path.join(BASE_DIR.parent, 'src-tauri'))
IS_PRODUCTION = os.getenv('ENVIRONMENT', 'development') == 'production'
ALLOW_INSECURE_LOCAL = os.getenv('ALLOW_INSECURE_LOCAL', 'False').lower() == 'true'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ahtru+th!b@60+qr3dv-e5tp-f+)w_^&46s14$7ke6i0#d$kj4')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
USE_POSTGRES = os.getenv('USE_POSTGRES', 'False').lower() == 'true'


#DEBUG = 'False'

# ============================================
# ALLOWED HOSTS - TAURI DESKTOP APP
# ============================================

DEFAULT_ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '0.0.0.0',
    '[::1]',  # IPv6 localhost
    '10.230.100.89',  # LAN access for mobile clients
    'www.pos.zathusystems.com', 'pos.zathusystems.com', 'pos3.express-travel-ticketing.online'
]

ALLOWED_HOSTS = list(
    dict.fromkeys(
        DEFAULT_ALLOWED_HOSTS
        + [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()]
    )
)

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    # Local apps
    'accounts',
    'business.apps.BusinessConfig',
    'staff',
    'subscription.apps.SubscriptionConfig',
    'affiliate',
    'inventory',
    'digitalmenu',
    'pos_sessions',
    'take_orders',
    'system_config',
    'mra_eis'
]

# ============================================
# JAZZMIN ADMIN CUSTOMIZATION
# ============================================

JAZZMIN_SETTINGS = {
    'site_title': 'HandyPOS Admin',
    'site_header': 'HandyPOS',
    'site_brand': 'HandyPOS',
    'site_logo': 'admin/img/handypos-mark.svg',
    'site_icon': 'admin/img/handypos-mark.svg',
    'welcome_sign': 'Welcome to HandyPOS Control Center',
    'copyright': 'HandyPOS',
    'search_model': ['accounts.User'],
    'show_sidebar': True,
    'navigation_expanded': True,
    'related_modal_active': True,
    'changeform_format': 'horizontal_tabs',
    'language_chooser': False,
    'icons': {
        'auth': 'fas fa-users-cog',
        'accounts': 'fas fa-id-badge',
        'business': 'fas fa-store',
        'staff': 'fas fa-user-tie',
        'subscription': 'fas fa-file-invoice-dollar',
        'affiliate': 'fas fa-handshake',
        'inventory': 'fas fa-boxes',
        'digitalmenu': 'fas fa-utensils',
        'pos_sessions': 'fas fa-cash-register',
        'take_orders': 'fas fa-receipt',
        'system_config': 'fas fa-cogs',
        'mra_eis': 'fas fa-file-signature',
    },
    'order_with_respect_to': [
        'accounts',
        'business',
        'staff',
        'subscription',
        'affiliate',
        'inventory',
        'digitalmenu',
        'pos_sessions',
        'take_orders',
        'system_config',
        'mra_eis',
    ],
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'dark_mode_theme': None,
    'navbar': 'navbar-white navbar-light',
    'navbar_fixed': True,
    'no_navbar_border': False,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_fixed': True,
    'sidebar_nav_compact_style': True,
    'sidebar_nav_flat_style': True,
    'sidebar_nav_child_indent': True,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'footer_fixed': False,
    'button_classes': {
        'primary': 'btn btn-primary',
        'secondary': 'btn btn-outline-secondary',
        'info': 'btn btn-info',
        'warning': 'btn btn-warning',
        'danger': 'btn btn-danger',
        'success': 'btn btn-success',
    },
}

# Use custom user model
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ============================================
# DATABASE CONFIGURATION
# ============================================

def _env_int(name, default):
    value = os.getenv(name, '').strip()
    if not value:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc


def _build_postgres_database():
    # Keep production DB settings explicit in this file (override with env vars if needed).
    sslmode = os.getenv('DB_SSLMODE', 'prefer').strip()
    database = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'handy_pos').strip(),
        'USER': os.getenv('DB_USER', 'postgres').strip(),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1').strip(),
        'PORT': os.getenv('DB_PORT', '5432').strip(),
        'CONN_MAX_AGE': _env_int('DB_CONN_MAX_AGE', 60),
    }
    if sslmode:
        database['OPTIONS'] = {'sslmode': sslmode}
    return database


def _build_database_settings():
    if DEBUG and not USE_POSTGRES:
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
                'OPTIONS': {
                    'timeout': _env_int('SQLITE_TIMEOUT_SECONDS', 30),
                },
            }
        }
    return {'default': _build_postgres_database()}


DATABASES = _build_database_settings()

# ============================================
# PASSWORD VALIDATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# INTERNATIONALIZATION
# ============================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================
# STATIC FILES
# ============================================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ============================================
# MEDIA FILES
# ============================================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ============================================
# DJANGO REST FRAMEWORK
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ============================================
# CORS CONFIGURATION - TAURI DESKTOP APP
# ============================================

CORS_ALLOW_ALL_ORIGINS = False
DEFAULT_CORS_ALLOWED_ORIGINS = [
    # Web development
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://0.0.0.0:3000',
    'http://0.0.0.0:8000',
    'http://10.230.100.89:3000',
    'http://10.230.100.89:8000',
    # Tauri desktop app
    'tauri://localhost',
    'tauri://127.0.0.1',
    # Tauri Android/Windows WebView origin
    'http://tauri.localhost',
    'https://tauri.localhost',
]
CORS_ALLOWED_ORIGINS = list(
    dict.fromkeys(
        DEFAULT_CORS_ALLOWED_ORIGINS
        + [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]
    )
)
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-handypos-device-serial',
]

# ============================================
# CSRF CONFIGURATION - TAURI DESKTOP APP
# ============================================

DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://0.0.0.0:3000',
    'http://0.0.0.0:8000',
    'http://10.230.100.89:3000',
    'http://10.230.100.89:8000',
    'tauri://localhost',
    'tauri://127.0.0.1',
    # Tauri Android/Windows WebView origin
    'http://tauri.localhost',
    'https://tauri.localhost',
]
CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(
        DEFAULT_CSRF_TRUSTED_ORIGINS
        + [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
    )
)

# ============================================
# JWT AUTHENTICATION
# ============================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# ============================================
# AUTHENTICATION BACKENDS
# ============================================

AUTHENTICATION_BACKENDS = [
    'accounts.auth_backend.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ============================================
# URL CONFIGURATION
# ============================================

# Disable APPEND_SLASH to prevent redirect issues with POST requests
APPEND_SLASH = False

# ============================================
# LOGGING CONFIGURATION
# ============================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ============================================
# SECURITY SETTINGS
# ============================================

if IS_DESKTOP_APP and DEBUG:
    # Development settings for desktop app - JWT auth, no CSRF needed
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    # Production settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        'default-src': ("'self'",),
        'script-src': ("'self'", "'unsafe-inline'"),
        'style-src': ("'self'", "'unsafe-inline'"),
    }

# ============================================
# CACHING CONFIGURATION
# ============================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'mwaka-pos-cache',
    }
}

# ============================================
# SESSION CONFIGURATION
# ============================================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ============================================
# FILE UPLOAD CONFIGURATION
# ============================================

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# ============================================
# MRA EIS CONFIGURATION
# ============================================

# Single cutover switch: keep TEST until go-live, then set to LIVE.
MRA_EIS_MODE = os.getenv('MRA_EIS_MODE', 'TEST').strip().upper()
if MRA_EIS_MODE not in {'TEST', 'LIVE'}:
    raise ImproperlyConfigured("MRA_EIS_MODE must be either 'TEST' or 'LIVE'.")

MRA_EIS_IS_LIVE = MRA_EIS_MODE == 'LIVE'

# Official MRA EIS API host (dev/sandbox or production)
MRA_EIS_BASE_URL = os.getenv(
    'MRA_EIS_BASE_URL',
    'https://eis-api.mra.mw' if MRA_EIS_IS_LIVE else 'https://dev-eis-api.mra.mw',
).rstrip('/')
MRA_EIS_TIMEOUT_SECONDS = int(os.getenv('MRA_EIS_TIMEOUT_SECONDS', '8'))
MRA_EIS_VERIFY_SSL = os.getenv('MRA_EIS_VERIFY_SSL', 'True').lower() == 'true'

# MRA onboarding access key for production TAC activation.
# The terminal signing secret is normally returned by the TAC activation response
# and stored on the Terminal record, not pre-filled here.
MRA_EIS_ACCESS_KEY = os.getenv('MRA_EIS_ACCESS_KEY', '')
MRA_EIS_SECRET_KEY = os.getenv('MRA_EIS_SECRET_KEY', '')
MRA_EIS_PRODUCT_ID = os.getenv('MRA_EIS_PRODUCT_ID', 'HandyPOS')
MRA_EIS_DEFAULT_SUPPLIER_ID = _env_int('MRA_EIS_DEFAULT_SUPPLIER_ID', 0) or None
MRA_EIS_CONFIG_MAX_AGE_HOURS = _env_int('MRA_EIS_CONFIG_MAX_AGE_HOURS', 24) or 24
MRA_EIS_SERVER_TIME_MAX_AGE_HOURS = _env_int('MRA_EIS_SERVER_TIME_MAX_AGE_HOURS', 24) or 24
MRA_EIS_REQUIRE_FRESH_CONFIG_FOR_SALES = os.getenv(
    'MRA_EIS_REQUIRE_FRESH_CONFIG_FOR_SALES',
    'True',
).lower() == 'true'
MRA_EIS_REQUIRE_OFFLINE_REPLAY_SEQUENCE_GUARD = os.getenv(
    'MRA_EIS_REQUIRE_OFFLINE_REPLAY_SEQUENCE_GUARD',
    'True',
).lower() == 'true'
MRA_EIS_REQUIRE_REMOTE_SEQUENCE_RECOVERY_FOR_SALES = os.getenv(
    'MRA_EIS_REQUIRE_REMOTE_SEQUENCE_RECOVERY_FOR_SALES',
    'True',
).lower() == 'true'
MRA_EIS_ALWAYS_OFFLINE_B2C = os.getenv(
    'MRA_EIS_ALWAYS_OFFLINE_B2C',
    'False',
).lower() == 'true'
MRA_EIS_ENFORCE_TERMINAL_DEVICE_BINDING = os.getenv(
    'MRA_EIS_ENFORCE_TERMINAL_DEVICE_BINDING',
    'True',
).lower() == 'true'
MRA_EIS_CHECK_TERMINAL_BLOCK_BEFORE_SALE = os.getenv(
    'MRA_EIS_CHECK_TERMINAL_BLOCK_BEFORE_SALE',
    'True',
).lower() == 'true'
MRA_EIS_VALIDATE_BUYER_TIN_BEFORE_SALE = os.getenv('MRA_EIS_VALIDATE_BUYER_TIN_BEFORE_SALE', 'True').lower() == 'true'
MRA_EIS_VALIDATE_VAT5_BEFORE_SALE = os.getenv('MRA_EIS_VALIDATE_VAT5_BEFORE_SALE', 'True').lower() == 'true'
MRA_EIS_ADJUST_STOCK_ON_VOID = os.getenv('MRA_EIS_ADJUST_STOCK_ON_VOID', 'True').lower() == 'true'
MRA_EIS_RECEIVE_STOCK_USE_GOODS_RECEIVING = os.getenv(
    'MRA_EIS_RECEIVE_STOCK_USE_GOODS_RECEIVING',
    'True',
).lower() == 'true'
MRA_EIS_STOCK_ADJUSTMENT_REASON_FALLBACK = os.getenv('MRA_EIS_STOCK_ADJUSTMENT_REASON_FALLBACK', 'Other')
MRA_EIS_STOCK_INCREASE_ADJUSTMENT_REASON = os.getenv('MRA_EIS_STOCK_INCREASE_ADJUSTMENT_REASON', '')
MRA_EIS_STOCK_DECREASE_ADJUSTMENT_REASON = os.getenv('MRA_EIS_STOCK_DECREASE_ADJUSTMENT_REASON', '')
MRA_EIS_MESSAGE_HASH_INPUT_MODE = os.getenv('MRA_EIS_MESSAGE_HASH_INPUT_MODE', 'canonical_json').strip().lower()
MRA_EIS_MESSAGE_HASH_INPUT_MODE_ALIASES = {
    'canonical': 'canonical_json',
    'canonical-json': 'canonical_json',
    'compact': 'compact_json',
    'compact-json': 'compact_json',
    'raw': 'raw_json',
    'raw-json': 'raw_json',
}
MRA_EIS_MESSAGE_HASH_INPUT_MODE = MRA_EIS_MESSAGE_HASH_INPUT_MODE_ALIASES.get(
    MRA_EIS_MESSAGE_HASH_INPUT_MODE,
    MRA_EIS_MESSAGE_HASH_INPUT_MODE,
)
if MRA_EIS_MESSAGE_HASH_INPUT_MODE not in {'canonical_json', 'compact_json', 'raw_json'}:
    raise ImproperlyConfigured(
        'MRA_EIS_MESSAGE_HASH_INPUT_MODE must be canonical_json, compact_json, or raw_json.'
    )
MRA_EIS_RECORD_MESSAGE_HASH_EVIDENCE = os.getenv(
    'MRA_EIS_RECORD_MESSAGE_HASH_EVIDENCE',
    'True',
).lower() == 'true'
MRA_EIS_LOG_MESSAGE_HASH_INPUT = os.getenv(
    'MRA_EIS_LOG_MESSAGE_HASH_INPUT',
    'False' if MRA_EIS_IS_LIVE else 'True',
).lower() == 'true'
MRA_EIS_MESSAGE_HASH_INPUT_CONFIRMED_BY_MRA = os.getenv(
    'MRA_EIS_MESSAGE_HASH_INPUT_CONFIRMED_BY_MRA',
    'False',
).lower() == 'true'

# Safety switches:
# - DRY_RUN=True: build payloads and mark records ready, but never submit to MRA
# - ENABLE_HTTP_CALLS=False: completely disable outbound MRA HTTP calls
# - ALLOW_LIVE_SUBMISSION=True: allow real submission once DRY_RUN is disabled
MRA_EIS_DRY_RUN = os.getenv('MRA_EIS_DRY_RUN', 'False' if MRA_EIS_IS_LIVE else 'True').lower() == 'true'
MRA_EIS_ENABLE_HTTP_CALLS = os.getenv('MRA_EIS_ENABLE_HTTP_CALLS', 'True').lower() == 'true'
MRA_EIS_ALLOW_LIVE_SUBMISSION = os.getenv(
    'MRA_EIS_ALLOW_LIVE_SUBMISSION',
    'True' if MRA_EIS_IS_LIVE else 'False',
).lower() == 'true'

# Keep compatibility with local TAC-based activation workflows if needed.
MRA_EIS_REQUIRE_LOCAL_TAC = os.getenv(
    'MRA_EIS_REQUIRE_LOCAL_TAC',
    'True' if MRA_EIS_IS_LIVE else 'False',
).lower() == 'true'

# In live mode, disallow static fallback product catalogs.
MRA_EIS_STRICT_PRODUCT_CODES = os.getenv(
    'MRA_EIS_STRICT_PRODUCT_CODES',
    'True' if MRA_EIS_IS_LIVE else 'False',
).lower() == 'true'

MRA_EIS_DEFAULT_CURRENCY = os.getenv('MRA_EIS_DEFAULT_CURRENCY', 'MWK')
MRA_EIS_INITIAL_INVENTORY_BATCH_SIZE = _env_int('MRA_EIS_INITIAL_INVENTORY_BATCH_SIZE', 50) or 50
MRA_EIS_OFFLINE_VALIDATION_BASE_URL = os.getenv(
    'MRA_EIS_OFFLINE_VALIDATION_BASE_URL',
    (
        'https://eis-portal.mra.mw/ReceiptValidation/Validate/'
        if MRA_EIS_IS_LIVE
        else 'https://dev-eis-portal.mra.mw/ReceiptValidation/Validate/'
    ),
).rstrip('/')

if MRA_EIS_IS_LIVE:
    if 'dev-eis-api' in MRA_EIS_BASE_URL.lower():
        raise ImproperlyConfigured('MRA_EIS_BASE_URL cannot point to dev while MRA_EIS_MODE=LIVE.')
    if MRA_EIS_DRY_RUN:
        raise ImproperlyConfigured('MRA_EIS_DRY_RUN must be False when MRA_EIS_MODE=LIVE.')
    if not MRA_EIS_ENABLE_HTTP_CALLS:
        raise ImproperlyConfigured('MRA_EIS_ENABLE_HTTP_CALLS must be True when MRA_EIS_MODE=LIVE.')
    if not MRA_EIS_ALLOW_LIVE_SUBMISSION:
        raise ImproperlyConfigured('MRA_EIS_ALLOW_LIVE_SUBMISSION must be True when MRA_EIS_MODE=LIVE.')
    if not MRA_EIS_PRODUCT_ID:
        raise ImproperlyConfigured('MRA_EIS_PRODUCT_ID must be a non-empty POS product ID.')
    if not MRA_EIS_VERIFY_SSL:
        raise ImproperlyConfigured('MRA_EIS_VERIFY_SSL must be True when MRA_EIS_MODE=LIVE.')

# Official endpoint map (overrideable via env)
MRA_EIS_ENDPOINTS = {
    'activate_terminal': os.getenv('MRA_EIS_ENDPOINT_ACTIVATE_TERMINAL', '/api/v1/onboarding/activate-terminal'),
    'confirm_terminal': os.getenv(
        'MRA_EIS_ENDPOINT_CONFIRM_TERMINAL',
        '/api/v1/onboarding/terminal-activated-confirmation'
    ),
    'report_sale': os.getenv('MRA_EIS_ENDPOINT_REPORT_SALE', '/api/v1/sales/submit-sales-transaction'),
    'report_sale_offline': os.getenv(
        'MRA_EIS_ENDPOINT_REPORT_SALE_OFFLINE',
        '/api/v1/sales/submit-sales-transaction'
    ),
    'get_last_online_transaction': os.getenv(
        'MRA_EIS_ENDPOINT_GET_LAST_ONLINE_TRANSACTION',
        '/api/v1/sales/last-submitted-online-transaction'
    ),
    'get_last_offline_transaction': os.getenv(
        'MRA_EIS_ENDPOINT_GET_LAST_OFFLINE_TRANSACTION',
        '/api/v1/sales/last-submitted-offline-transaction'
    ),
    'request_new_terminal_token': os.getenv(
        'MRA_EIS_ENDPOINT_REQUEST_NEW_TERMINAL_TOKEN',
        '/api/v1/configuration/request-new-terminal-token'
    ),
    'process_credit_debit_note': os.getenv(
        'MRA_EIS_ENDPOINT_PROCESS_CREDIT_DEBIT_NOTE',
        '/api/v1/sales/process-credit-debit-note'
    ),
    'get_invoice_by_number': os.getenv(
        'MRA_EIS_ENDPOINT_GET_INVOICE_BY_NUMBER',
        '/api/v1/sales/get-invoice-by-number'
    ),
    'product_status': os.getenv('MRA_EIS_ENDPOINT_PRODUCT_STATUS', '/api/v1/utilities/product-status'),
    'ping': os.getenv('MRA_EIS_ENDPOINT_PING', '/api/v1/utilities/ping'),
    'initial_inventory_upload': os.getenv(
        'MRA_EIS_ENDPOINT_INITIAL_INVENTORY_UPLOAD',
        '/api/v1/utilities/taxpayer-initial-inventory-upload'
    ),
    'get_terminal_site_products': os.getenv(
        'MRA_EIS_ENDPOINT_GET_TERMINAL_SITE_PRODUCTS',
        '/api/v1/utilities/get-terminal-site-products'
    ),
    'transfer_inventory': os.getenv(
        'MRA_EIS_ENDPOINT_TRANSFER_INVENTORY',
        '/api/v1/stock/transfer-inventory'
    ),
    'warehouse_inventory': os.getenv(
        'MRA_EIS_ENDPOINT_WAREHOUSE_INVENTORY',
        '/api/v1/stock/warehouse-inventory'
    ),
    'raw_material_inventory': os.getenv(
        'MRA_EIS_ENDPOINT_RAW_MATERIAL_INVENTORY',
        '/api/v1/raw-material/get-raw-material'
    ),
    'submit_informal_purchase': os.getenv(
        'MRA_EIS_ENDPOINT_SUBMIT_INFORMAL_PURCHASE',
        '/api/v1/stock/submit-informal-purchase'
    ),
    'submit_raw_material_conversion': os.getenv(
        'MRA_EIS_ENDPOINT_SUBMIT_RAW_MATERIAL_CONVERSION',
        '/api/v1/raw-material/submit-conversion'
    ),
    'submit_stock_adjustment': os.getenv(
        'MRA_EIS_ENDPOINT_SUBMIT_STOCK_ADJUSTMENT',
        '/api/v1/stock/submit-adjustment'
    ),
    'get_stock_adjustment_reasons': os.getenv(
        'MRA_EIS_ENDPOINT_GET_STOCK_ADJUSTMENT_REASONS',
        '/api/v1/stock/getStockAdjustmentReasons'
    ),
    'get_suppliers': os.getenv('MRA_EIS_ENDPOINT_GET_SUPPLIERS', '/api/v1/stock/get-suppliers'),
    'add_product': os.getenv('MRA_EIS_ENDPOINT_ADD_PRODUCT', '/api/v1/stock/add-product'),
    'get_hs_codes': os.getenv('MRA_EIS_ENDPOINT_GET_HS_CODES', '/api/v1/stock/get-hs-codes'),
    'get_units_of_measure': os.getenv(
        'MRA_EIS_ENDPOINT_GET_UNITS_OF_MEASURE',
        '/api/v1/stock/get-units-of-measure'
    ),
    'sync_product_status': os.getenv('MRA_EIS_ENDPOINT_SYNC_PRODUCT_STATUS', '/api/v1/utilities/product-status'),
    'get_latest_config': os.getenv(
        'MRA_EIS_ENDPOINT_GET_LATEST_CONFIG',
        '/api/v1/configuration/get-latest-configs'
    ),
    'get_terminal_blocking_message': os.getenv(
        'MRA_EIS_ENDPOINT_GET_TERMINAL_BLOCKING_MESSAGE',
        '/api/v1/utilities/get-terminal-blocking-message'
    ),
    'check_terminal_unblock_status': os.getenv(
        'MRA_EIS_ENDPOINT_CHECK_TERMINAL_UNBLOCK_STATUS',
        '/api/v1/utilities/check-terminal-unblock-status'
    ),
    'check_tin_authorization_requirement': os.getenv(
        'MRA_EIS_ENDPOINT_CHECK_TIN_AUTHORIZATION_REQUIREMENT',
        '/api/v1/utilities/check-tin-authorization-requirement'
    ),
    'validate_authorization_code': os.getenv(
        'MRA_EIS_ENDPOINT_VALIDATE_AUTHORIZATION_CODE',
        '/api/v1/utilities/validate-authorization-code'
    ),
    'validate_vat5': os.getenv(
        'MRA_EIS_ENDPOINT_VALIDATE_VAT5',
        '/api/v1/utilities/validate-vat5-certificate'
    ),
    'cancel_receipt': os.getenv('MRA_EIS_ENDPOINT_CANCEL_RECEIPT', '/api/v1/sales/cancel-receipt'),
    'get_void_receipts': os.getenv('MRA_EIS_ENDPOINT_GET_VOID_RECEIPTS', '/api/v1/sales/get-void-receipts'),
}

# ============================================
# EMAIL CONFIGURATION (Optional)
# ============================================

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 1025))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mwakapos.local')

# ============================================
# CELERY CONFIGURATION (Optional)
# ============================================

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Periodic EIS background processing. This is the compliance path for
# offline B2C replay; frontend sync is only a convenience trigger.
MRA_EIS_SYNC_INTERVAL_MINUTES = int(os.getenv('MRA_EIS_SYNC_INTERVAL_MINUTES', '5'))
MRA_EIS_RETRY_INTERVAL_MINUTES = int(os.getenv('MRA_EIS_RETRY_INTERVAL_MINUTES', '2'))
MRA_EIS_SYNC_ALL_ACTIVE_TERMINALS = os.getenv(
    'MRA_EIS_SYNC_ALL_ACTIVE_TERMINALS',
    'True',
).lower() == 'true'

if crontab:
    CELERY_BEAT_SCHEDULE = {
        'mra-eis-sync-offline-invoices': {
            'task': 'mra_eis.tasks.sync_offline_invoices_for_online_terminals',
            'schedule': crontab(minute=f'*/{MRA_EIS_SYNC_INTERVAL_MINUTES}'),
        },
        'mra-eis-process-retry-queue': {
            'task': 'mra_eis.tasks.process_mra_retry_queue',
            'schedule': crontab(minute=f'*/{MRA_EIS_RETRY_INTERVAL_MINUTES}'),
        },
    }

# ============================================
# SENTRY CONFIGURATION (Optional)
# ============================================

SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and IS_PRODUCTION:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,
            send_default_pii=False,
        )
    except ImportError:
        pass
