# Generated by Django 6.0 on 2026-02-04 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0014_invoiceline_remove_invoice_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRAInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.BigIntegerField(help_text='Sequential invoice number per terminal')),
                ('mra_invoice_id', models.CharField(blank=True, help_text='Invoice ID assigned by MRA', max_length=255)),
                ('seller_tin', models.CharField(help_text='Client TIN (always used as seller)', max_length=50)),
                ('seller_name', models.CharField(max_length=255)),
                ('buyer_tin', models.CharField(blank=True, help_text='Buyer TIN (if available)', max_length=50)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(help_text='Invoice items with MRA product codes and tax info')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_breakdown', models.JSONField(default=dict, help_text='Tax by category: {standard: amount, zero: amount, exempt: amount}')),
                ('invoice_signature', models.CharField(blank=True, help_text='Cryptographic signature of invoice', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to MRA'), ('accepted', 'Accepted by MRA'), ('rejected', 'Rejected by MRA'), ('offline_queued', 'Queued for Offline Sync'), ('offline_synced', 'Synced from Offline Queue')], default='draft', max_length=20)),
                ('is_online', models.BooleanField(default=True, help_text='True if submitted online, False if offline')),
                ('invoice_date', models.DateTimeField(help_text='Invoice date/time')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mra_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_invoices', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_invoices', to='business.business')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_id', models.CharField(help_text='Unique terminal identifier assigned by MRA', max_length=50, unique=True)),
                ('device_serial', models.CharField(help_text='Device serial number or generated identifier', max_length=255)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address of the device', max_length=17)),
                ('pos_name', models.CharField(help_text='Name of POS system', max_length=255)),
                ('pos_version', models.CharField(help_text='Version of POS system', max_length=50)),
                ('os_type', models.CharField(help_text='Operating system type (Windows, Linux, macOS, Android, iOS, Web)', max_length=50)),
                ('mra_terminal_id', models.CharField(help_text='Terminal ID from MRA', max_length=255, unique=True)),
                ('mra_api_key', models.CharField(help_text='API key for MRA communication (should be encrypted)', max_length=500)),
                ('mra_token', models.TextField(blank=True, help_text='Current authentication token from MRA')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('status', models.CharField(choices=[('pending_activation', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending_activation', max_length=20)),
                ('is_online', models.BooleanField(default=False, help_text='Current connectivity status')),
                ('online_invoice_counter', models.BigIntegerField(default=0, help_text='Sequential counter for online invoices')),
                ('offline_invoice_counter', models.BigIntegerField(default=0, help_text='Sequential counter for offline invoices')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_terminals', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_terminals', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncRetryQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('submit_invoice', 'Submit Invoice'), ('sync_offline_invoices', 'Sync Offline Invoices'), ('refresh_token', 'Refresh Token'), ('fetch_configuration', 'Fetch Configuration')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_retry_queue', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['next_attempt_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineInvoiceQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_position', models.BigIntegerField(help_text='Position in offline queue (for sequential sync)')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('mra_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue_entry', to='mra_eis.mrainvoice')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_queue', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['queue_position'],
            },
        ),
        migrations.CreateModel(
            name='OfflineAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('invoice_created', 'Invoice Created Offline'), ('invoice_queued', 'Invoice Queued'), ('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('online_detected', 'Online Detected'), ('offline_detected', 'Offline Detected')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_audit_logs', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mrainvoice',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mra_invoices', to='mra_eis.terminal'),
        ),
        migrations.CreateModel(
            name='MRAAPIError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(choices=[('connection_error', 'Connection Error'), ('timeout', 'Timeout'), ('token_expired', 'Token Expired'), ('invalid_request', 'Invalid Request'), ('server_error', 'Server Error'), ('rate_limit', 'Rate Limit'), ('unknown', 'Unknown Error')], max_length=50)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mra_eis.mrainvoice')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_errors', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Activation code from MRA', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='unused', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='TAC expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_tacs', to='business.business')),
                ('used_by_terminal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_code', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('activated', 'Terminal Activated'), ('token_refreshed', 'Token Refreshed'), ('online_status_changed', 'Online Status Changed'), ('configuration_updated', 'Configuration Updated'), ('suspended', 'Terminal Suspended'), ('deactivated', 'Terminal Deactivated')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='mra_eis.terminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('config_types', models.JSONField(default=list, help_text='List of config types synced')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_config_sync_logs', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='mra_eis_con_busines_13e697_idx'), models.Index(fields=['created_at'], name='mra_eis_con_created_92f5f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MRAConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_type', models.CharField(choices=[('tax_rules', 'Tax Rules'), ('receipt_format', 'Receipt Format'), ('product_codes', 'Product Codes'), ('system_settings', 'System Settings')], max_length=50)),
                ('config_version', models.CharField(help_text='Version identifier from MRA', max_length=50)),
                ('config_data', models.JSONField(help_text='Configuration data from MRA')),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fetched_from_mra_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_configs', to='business.business')),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['business', 'config_type', 'is_active'], name='mra_eis_mra_busines_55d9cb_idx'), models.Index(fields=['config_type', 'effective_from'], name='mra_eis_mra_config__029c5c_idx')],
                'unique_together': {('business', 'config_type', 'config_version')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Invoice Created'), ('submitted', 'Invoice Submitted'), ('accepted', 'Invoice Accepted by MRA'), ('rejected', 'Invoice Rejected by MRA'), ('queued_offline', 'Queued for Offline Sync'), ('synced_from_offline', 'Synced from Offline Queue'), ('viewed', 'Invoice Viewed'), ('receipt_generated', 'Receipt Generated')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mra_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='mra_eis.mrainvoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mra_invoice', 'action'], name='mra_eis_inv_mra_inv_80cf07_idx'), models.Index(fields=['created_at'], name='mra_eis_inv_created_b892eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MRAProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_item_id', models.CharField(help_text='UUID of the internal inventory item', max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('mra_product_code', models.CharField(help_text='MRA-assigned product code', max_length=50)),
                ('mra_product_name', models.CharField(max_length=255)),
                ('tax_category', models.CharField(choices=[('standard', 'Standard Rated (16.5%)'), ('zero', 'Zero Rated (0%)'), ('exempt', 'Exempt')], max_length=20)),
                ('approved_price', models.DecimalField(decimal_places=2, help_text='MRA-approved price (if applicable)', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage', max_digits=5)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mra_product_mappings', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='mra_eis_mra_busines_44b8e1_idx'), models.Index(fields=['mra_product_code'], name='mra_eis_mra_mra_pro_f08fb2_idx')],
                'unique_together': {('business', 'inventory_item_id')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50)),
                ('receipt_text', models.TextField(help_text='Formatted receipt text')),
                ('qr_code_data', models.TextField(help_text='Data encoded in QR code (invoice signature + metadata)')),
                ('qr_code_image', models.TextField(blank=True, help_text='Base64 encoded QR code image')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('mra_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='mra_eis.mrainvoice')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['mra_invoice'], name='mra_eis_rec_mra_inv_abd2a4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['business', 'branch'], name='mra_eis_ter_busines_8e7f00_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['status'], name='mra_eis_ter_status_c65d95_idx'),
        ),
        migrations.AddIndex(
            model_name='terminal',
            index=models.Index(fields=['mra_terminal_id'], name='mra_eis_ter_mra_ter_acf620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('business', 'branch')},
        ),
        migrations.AddIndex(
            model_name='syncretryqueue',
            index=models.Index(fields=['terminal', 'status'], name='mra_eis_syn_termina_427206_idx'),
        ),
        migrations.AddIndex(
            model_name='syncretryqueue',
            index=models.Index(fields=['next_attempt_at'], name='mra_eis_syn_next_at_f8e59a_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineinvoicequeue',
            index=models.Index(fields=['terminal', 'status'], name='mra_eis_off_termina_189fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineinvoicequeue',
            index=models.Index(fields=['queue_position'], name='mra_eis_off_queue_p_5bfb52_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offlineinvoicequeue',
            unique_together={('terminal', 'queue_position')},
        ),
        migrations.AddIndex(
            model_name='offlineauditlog',
            index=models.Index(fields=['terminal', 'event_type'], name='mra_eis_off_termina_7208dc_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineauditlog',
            index=models.Index(fields=['created_at'], name='mra_eis_off_created_1de5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['business', 'branch'], name='mra_eis_mra_busines_06c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['terminal', 'invoice_number'], name='mra_eis_mra_termina_0507c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['status'], name='mra_eis_mra_status_f38db4_idx'),
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['invoice_date'], name='mra_eis_mra_invoice_42e343_idx'),
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['seller_tin'], name='mra_eis_mra_seller__47ad4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mrainvoice',
            unique_together={('terminal', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='mraapierror',
            index=models.Index(fields=['terminal', 'is_resolved'], name='mra_eis_mra_termina_80f4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='mraapierror',
            index=models.Index(fields=['error_type'], name='mra_eis_mra_error_t_725f12_idx'),
        ),
        migrations.AddIndex(
            model_name='mraapierror',
            index=models.Index(fields=['created_at'], name='mra_eis_mra_created_44fc37_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalactivationcode',
            index=models.Index(fields=['business', 'status'], name='mra_eis_ter_busines_dc7fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalactivationcode',
            index=models.Index(fields=['code'], name='mra_eis_ter_code_761f94_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalauditlog',
            index=models.Index(fields=['terminal', 'action'], name='mra_eis_ter_termina_3c0592_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalauditlog',
            index=models.Index(fields=['created_at'], name='mra_eis_ter_created_a98b8b_idx'),
        ),
    ]
