# Generated by Django 6.0 on 2026-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_branch_is_dirty_business_is_dirty_and_more'),
        ('mra_eis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mrainvoice',
            unique_together={('terminal', 'invoice_number', 'is_online')},
        ),
        migrations.AddIndex(
            model_name='mrainvoice',
            index=models.Index(fields=['terminal', 'invoice_number', 'is_online'], name='mra_eis_mra_termina_2e91b0_idx'),
        ),
    ]
