# Generated by Django 4.2.11 on 2026-01-12 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_alter_branch_id_alter_business_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('order_type', models.CharField(choices=[('sale', 'POS Sale'), ('kitchen', 'Kitchen Preparation')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('On Account', 'On Account'), ('Other', 'Other')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_float', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mobile_money_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_on_account_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tips', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_stock', models.JSONField(blank=True, default=list)),
                ('closing_stock', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_sessions.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos_sessions.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['branch', 'status'], name='pos_session_branch__e245b9_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'status'], name='pos_session_user_id_5d3c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['started_at'], name='pos_session_started_209899_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='pos_session_order_i_8c6bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['inventory_item_id'], name='pos_session_invento_43a2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='pos_session_branch__48cba1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'order_type'], name='pos_session_branch__318500_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session'], name='pos_session_session_d9a00a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='pos_session_created_0973d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('branch', 'order_number')},
        ),
    ]
