# Generated by Django 6.0 on 2026-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0002_order_invoice_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('sale', 'POS Sale'), ('kitchen', 'Kitchen Preparation'), ('invoice', 'Invoice Sale')], default='sale', max_length=20),
        ),
    ]
