# Generated by Django 6.0 on 2026-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0003_alter_order_order_type'),
        ('pos_sessions', '0003_remove_old_tax_fields'),
    ]

    operations = [
    ]
