# Generated by Django 6.0 on 2026-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_invoiceline_remove_invoice_items_and_more'),
        ('pos_sessions', '0004_merge_20260124_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Digital signature from MRA', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eis_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', help_text='MRA EIS submission status', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='eis_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When was this submitted to MRA?', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='eis_uuid',
            field=models.CharField(blank=True, help_text='EIS-assigned UUID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fiscal_invoice_number',
            field=models.CharField(blank=True, help_text='Fiscal invoice number for MRA', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_fiscal_locked',
            field=models.BooleanField(default=False, help_text='Is this fiscal invoice locked? (immutable)'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code_payload',
            field=models.TextField(blank=True, help_text='QR code data from MRA', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mra_product_code',
            field=models.CharField(blank=True, help_text='MRA product code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Rated'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt')], default='STANDARD', help_text='VAT category for this item', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fiscal_invoice_number'], name='pos_session_fiscal__563a08_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['eis_status'], name='pos_session_eis_sta_7d44cb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['mra_product_code'], name='pos_session_mra_pro_b51fe2_idx'),
        ),
    ]
