# Generated by Django 6.0 on 2026-02-13 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_branch_is_dirty_business_is_dirty_and_more'),
        ('pos_sessions', '0005_order_digital_signature_order_eis_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_dirty'], name='pos_session_is_dirt_878650_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_dirty'], name='pos_session_is_dirt_1d15ff_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_dirty'], name='pos_session_is_dirt_285e36_idx'),
        ),
    ]
