# Generated by Django 6.0 on 2026-02-18 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_branch_is_dirty_business_is_dirty_and_more'),
        ('pos_sessions', '0006_order_is_dirty_orderitem_is_dirty_session_is_dirty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eis_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='eis_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eis_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fiscal_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_dirty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_fiscal_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_invoice_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_code_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Voided', 'Voided'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_rate_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('VAT_STANDARD', 'VAT Standard Rated'), ('VAT_ZERO', 'VAT Zero Rated'), ('VAT_EXEMPT', 'VAT Exempt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_dirty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mra_product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard Rated'), ('ZERO', 'Zero Rated'), ('EXEMPT', 'Exempt')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(choices=[('return', 'Sales Return'), ('refund', 'Customer Refund'), ('discount', 'Discount Adjustment'), ('error', 'Invoice Error Correction')], max_length=20)),
                ('description', models.TextField()),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_credit_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('eis_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('eis_status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', max_length=20)),
                ('eis_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_payload', models.TextField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('is_fiscal_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='pos_sessions.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'eis_status'], name='pos_session_branch__32c9dd_idx'), models.Index(fields=['original_order'], name='pos_session_origina_4cb5c4_idx'), models.Index(fields=['fiscal_credit_number'], name='pos_session_fiscal__968a80_idx'), models.Index(fields=['is_dirty'], name='pos_session_is_dirt_85998b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('additional_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_debit_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('eis_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('eis_status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', max_length=20)),
                ('eis_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_payload', models.TextField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('is_fiscal_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='pos_sessions.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'eis_status'], name='pos_session_branch__306596_idx'), models.Index(fields=['original_order'], name='pos_session_origina_62c95f_idx'), models.Index(fields=['fiscal_debit_number'], name='pos_session_fiscal__4137a4_idx'), models.Index(fields=['is_dirty'], name='pos_session_is_dirt_b4546d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoidTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('void_number', models.CharField(max_length=100, unique=True)),
                ('void_reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('item_returned', 'Item Returned'), ('wrong_order', 'Wrong Order'), ('system_error', 'System Error'), ('duplicate', 'Duplicate Entry'), ('payment_failed', 'Payment Failed'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(help_text='Detailed explanation of why the sale was voided')),
                ('voided_amount', models.DecimalField(decimal_places=2, help_text='Total amount voided', max_digits=12)),
                ('voided_vat', models.DecimalField(decimal_places=2, help_text='VAT amount voided', max_digits=12)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash Refund'), ('card', 'Card Refund'), ('credit', 'Store Credit'), ('none', 'No Refund')], default='none', help_text='How the customer will be refunded', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be refunded to customer', max_digits=12)),
                ('refund_processed', models.BooleanField(default=False, help_text='Has the refund been processed?')),
                ('refund_processed_at', models.DateTimeField(blank=True, help_text='When was refund processed?', null=True)),
                ('fiscal_void_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('eis_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('eis_status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', max_length=20)),
                ('eis_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_payload', models.TextField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('is_fiscal_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_dirty', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_transactions', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_transactions', to='business.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_transactions', to='pos_sessions.order')),
                ('refund_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_transactions_refunded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'eis_status'], name='pos_session_branch__a3f9ff_idx'), models.Index(fields=['original_order'], name='pos_session_origina_1543af_idx'), models.Index(fields=['fiscal_void_number'], name='pos_session_fiscal__9f6f10_idx'), models.Index(fields=['refund_processed'], name='pos_session_refund__8dadb1_idx'), models.Index(fields=['is_dirty'], name='pos_session_is_dirt_14e593_idx')],
            },
        ),
    ]
