# Generated by Django 6.0 on 2026-02-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0007_alter_order_digital_signature_alter_order_eis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net amount (before tax)', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount for this item', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_calculation_method',
            field=models.CharField(choices=[('inclusive', 'Tax Inclusive (Price includes tax)'), ('exclusive', 'Tax Exclusive (Tax added to price)')], default='inclusive', help_text='How tax is calculated for this item (Immutable snapshot)', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate percentage (e.g., 16.50 for 16.5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Rated'), ('zero', 'Zero Rated'), ('exempt', 'Exempt')], default='standard', help_text='MRA tax classification', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross amount (subtotal + tax)', max_digits=12),
        ),
    ]
