# Generated by Django 4.2.11 on 2026-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_sessions', '0008_orderitem_price_orderitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch_consumption',
            field=models.JSONField(blank=True, default=list, help_text='Exact batch consumption trace for this order line. Each entry: {inventory_item_id, batch_id, quantity}.'),
        ),
    ]
