# Generated by Django 4.2.11 on 2026-01-14 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0006_alter_branch_id_alter_business_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_orders', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_orders', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='take_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TakeOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('take_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='take_orders.takeorder')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['take_order'], name='take_orders_take_or_a2c691_idx'), models.Index(fields=['inventory_item_id'], name='take_orders_invento_439122_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['branch', 'status'], name='take_orders_branch__5e57e6_idx'),
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['branch', 'created_at'], name='take_orders_branch__53dc81_idx'),
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['created_by'], name='take_orders_created_f1f36c_idx'),
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['status'], name='take_orders_status_6e0f76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='takeorder',
            unique_together={('branch', 'order_number')},
        ),
    ]
