# Generated by Django 6.0 on 2026-01-22 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_expense_invoice_approval_status_invoice_approved_at_and_more'),
        ('take_orders', '0002_takeorderitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='takeorder',
            name='order_type',
            field=models.CharField(choices=[('staff', 'Staff Created'), ('self_service', 'Self-Service')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='takeorder',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['branch', 'order_type'], name='take_orders_branch__550f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='takeorder',
            index=models.Index(fields=['order_type'], name='take_orders_order_t_d00a33_idx'),
        ),
    ]
