# Generated by Django 6.0 on 2026-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_orders', '0003_takeorder_order_type_takeorder_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Sent to Kitchen', 'Sent to Kitchen'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
