# Generated by Django 6.0 on 2026-01-06 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
        ('subscription', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_affiliate_program', models.BooleanField(default=True)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('default_commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('referral_expiry_days', models.IntegerField(default=30)),
                ('min_commission_for_payout', models.DecimalField(decimal_places=2, default=50.0, max_digits=12)),
                ('commission_on_signup', models.BooleanField(default=True)),
                ('commission_on_first_purchase', models.BooleanField(default=True)),
                ('commission_on_subscription', models.BooleanField(default=True)),
                ('commission_on_monthly_recurring', models.BooleanField(default=False)),
                ('auto_payout_enabled', models.BooleanField(default=False)),
                ('auto_payout_day', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Affiliate Settings',
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('total_referred_businesses', models.IntegerField(default=0)),
                ('total_active_referrals', models.IntegerField(default=0)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.CreateModel(
            name='AffiliatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='affiliate.affiliate')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('referral_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_referrals', to='affiliate.affiliate')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('commission_type', models.CharField(choices=[('signup_bonus', 'Sign Up Bonus'), ('first_month', 'First Month'), ('monthly_recurring', 'Monthly Recurring')], default='monthly_recurring', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('billing_month', models.DateField()),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_commissions', to='affiliate.affiliate')),
                ('business_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='affiliate.businessreferral')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='subscription.subscription')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('business_referral', 'billing_month')},
            },
        ),
    ]
