# Generated by Django 6.0 on 2026-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_alter_affiliate_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringcommission',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate used for this calculation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recurringcommission',
            name='commission_rate_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Type of commission rate (percentage or fixed)', max_length=20, null=True),
        ),
    ]
