# Generated by Django 4.2.11 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0013_sync_affiliate_total_paid_from_completed_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='residence_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='residence_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='residence_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
