# Generated by Django 4.2.11 on 2026-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0014_affiliate_residence_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliate",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="affiliate_profile_pictures/"),
        ),
    ]
