# Generated by Django 4.2.11 on 2026-03-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0015_affiliate_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatesettings",
            name="whatsapp_group_link",
            field=models.URLField(blank=True),
        ),
    ]
