# Generated by Django 6.0 on 2026-01-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_busines_1bf903_idx',
            old_name='inventory_i_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_status_77888d_idx',
            old_name='inventory_i_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='inventory_i_item_ty_72ee4a_idx',
            old_name='inventory_i_item_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='inventory_p_busines_b02c2f_idx',
            old_name='inventory_p_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='inventory_p_supplie_1bb150_idx',
            old_name='inventory_p_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='inventory_p_status_43427b_idx',
            old_name='inventory_p_status_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='inventory_p_purchas_55a2cf_idx',
            old_name='inventory_p_purchas_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='inventory_p_invento_538127_idx',
            old_name='inventory_p_invento_idx',
        ),
        migrations.RenameIndex(
            model_name='stockaudit',
            new_name='inventory_s_branch__eea052_idx',
            old_name='inventory_s_branch__idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_from_br_8a09fb_idx',
            old_name='inventory_s_from_br_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_to_bran_49ccd8_idx',
            old_name='inventory_s_to_bran_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterecord',
            new_name='inventory_w_branch__c09cac_idx',
            old_name='inventory_w_branch__idx',
        ),
        migrations.RenameIndex(
            model_name='wasterecord',
            new_name='inventory_w_reason_c24361_idx',
            old_name='inventory_w_reason_idx',
        ),
    ]
