# Generated by Django 6.0 on 2026-01-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_barcode_and_more'),
    ]

    # IDs are created as UUIDs in 0001_initial for fresh databases.
    # Keep this migration as a no-op to preserve migration history compatibility.
    operations = []
