# Generated by Django 4.2.11 on 2026-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_id_alter_purchaseorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
