# Generated by Django 6.0 on 2026-01-14 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_branch_id_alter_business_id_and_more'),
        ('inventory', '0006_inventoryitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('STOCK_WASTE', 'Stock Waste'), ('STOCK_RECEIVE', 'Stock Receive'), ('STOCK_TRANSFER', 'Stock Transfer'), ('STOCK_AUDIT', 'Stock Audit'), ('INVENTORY_UPDATE', 'Inventory Update')], max_length=50)),
                ('entity_type', models.CharField(choices=[('WasteRecord', 'Waste Record'), ('PurchaseOrder', 'Purchase Order'), ('StockTransfer', 'Stock Transfer'), ('InventoryItem', 'Inventory Item')], max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='inventory_a_busines_63eaed_idx'), models.Index(fields=['branch', 'created_at'], name='inventory_a_branch__00fadf_idx'), models.Index(fields=['action_type'], name='inventory_a_action__ef09d3_idx'), models.Index(fields=['entity_type'], name='inventory_a_entity__323a0f_idx')],
            },
        ),
    ]
