# Generated by Django 6.0 on 2026-01-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_purchaseorder_order_number_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_produced',
            field=models.BooleanField(default=False),
        ),
    ]
