# Generated by Django 6.0 on 2026-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_is_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_sold_in_portions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='portion_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='portions_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
