# Generated by Django 6.0 on 2026-02-04 18:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_taxrate_one_active_default_tax_per_business_and_more'),
        ('inventory', '0012_alter_purchaseorder_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_before_sale', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_sold', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_after_sale', models.DecimalField(decimal_places=3, max_digits=12)),
                ('related_invoice_number', models.CharField(help_text='Invoice number this snapshot is linked to', max_length=100)),
                ('related_order_id', models.CharField(blank=True, help_text='POS order ID', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_tax_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRAProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mra_product_code', models.CharField(help_text='MRA-assigned product code', max_length=100, unique=True)),
                ('mra_product_name', models.CharField(help_text='MRA-approved product name', max_length=255)),
                ('mra_tax_type', models.CharField(choices=[('standard', 'Standard Rated (16.5%)'), ('zero', 'Zero Rated (0%)'), ('exempt', 'Exempt')], help_text='MRA tax classification', max_length=20)),
                ('mra_tax_rate', models.DecimalField(decimal_places=2, help_text='MRA tax rate (immutable)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mra_unit_measure', models.CharField(choices=[('unit', 'Unit'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('meter', 'Meter'), ('box', 'Box'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton')], default='unit', help_text='MRA unit of measure', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Has MRA approved this mapping?')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When was this mapping approved?', null=True)),
                ('mra_synced', models.BooleanField(default=False, help_text='Has this been synced to MRA?')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='mra_reference',
            field=models.CharField(blank=True, help_text='MRA invoice or reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='mra_related',
            field=models.BooleanField(default=False, help_text='Is this operation related to MRA?'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='Is price locked by MRA? (prevents local changes)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tax_locked',
            field=models.BooleanField(default=True, help_text='Is tax rate locked? (should always be True for sellables)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_tin',
            field=models.CharField(blank=True, help_text='Supplier TIN for VAT reclaim', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_vat_registered',
            field=models.BooleanField(default=False, help_text='Is supplier VAT registered?'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='approval_role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Auditor', 'Auditor'), ('MRA', 'MRA Official')], help_text='Role of person approving audit', max_length=50),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='inventory_locked',
            field=models.BooleanField(default=False, help_text='Is inventory locked after approval?'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='mra_visible',
            field=models.BooleanField(default=True, help_text='Is this audit visible to MRA?'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='mra_notified',
            field=models.BooleanField(default=False, help_text='Has MRA been notified of this transfer?'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_reference',
            field=models.CharField(blank=True, help_text='Unique transfer reference for MRA', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_tin',
            field=models.CharField(blank=True, help_text="Supplier's Tax Identification Number (for VAT reclaim)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Is supplier VAT registered?'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='affects_tax',
            field=models.BooleanField(default=False, help_text='Does this waste affect tax reporting?'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Manager/Auditor who approved this waste', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('STOCK_WASTE', 'Stock Waste'), ('STOCK_RECEIVE', 'Stock Receive'), ('STOCK_TRANSFER', 'Stock Transfer'), ('STOCK_AUDIT', 'Stock Audit'), ('INVENTORY_UPDATE', 'Inventory Update'), ('PRICE_CHANGE', 'Price Change'), ('TAX_CHANGE', 'Tax Change'), ('MRA_SYNC', 'MRA Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audit_logs', to='business.branch'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audit_logs', to='business.business'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('WasteRecord', 'Waste Record'), ('PurchaseOrder', 'Purchase Order'), ('StockTransfer', 'Stock Transfer'), ('InventoryItem', 'Inventory Item'), ('MRAProductMapping', 'MRA Product Mapping'), ('InventorySnapshot', 'Inventory Snapshot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_units',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['mra_related'], name='inventory_a_mra_rel_0786a5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['mra_reference'], name='inventory_a_mra_ref_59e3de_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_c7bf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier_tin'], name='inventory_p_supplie_21f9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['mra_visible'], name='inventory_s_mra_vis_d49109_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_reference'], name='inventory_s_transfe_f66e43_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'is_active'], name='inventory_s_busines_47c58a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_tin'], name='inventory_s_supplie_21e01f_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['affects_tax'], name='inventory_w_affects_fa5024_idx'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='business.branch'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='mraproductmapping',
            name='inventory_item',
            field=models.OneToOneField(help_text='Link to internal inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='mra_mapping', to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['inventory_item', 'branch'], name='inventory_i_invento_31ecbd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['related_invoice_number'], name='inventory_i_related_66eea2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['created_at'], name='inventory_i_created_a08d44_idx'),
        ),
        migrations.AddIndex(
            model_name='mraproductmapping',
            index=models.Index(fields=['mra_product_code'], name='inventory_m_mra_pro_b299b7_idx'),
        ),
        migrations.AddIndex(
            model_name='mraproductmapping',
            index=models.Index(fields=['is_approved'], name='inventory_m_is_appr_09dfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='mraproductmapping',
            index=models.Index(fields=['mra_synced'], name='inventory_m_mra_syn_1a172b_idx'),
        ),
    ]
