# Generated by Django 6.0 on 2026-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorysnapshot_mraproductmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(blank=True, help_text='Unique product code for identification', max_length=100, null=True, unique=True),
        ),
    ]
