# Generated by Django 6.0 on 2026-02-13 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_branch_is_dirty_business_is_dirty_and_more'),
        ('inventory', '0014_inventoryitem_product_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='stockaudititem',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_dirty'], name='inventory_a_is_dirt_caff91_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_dirty'], name='inventory_i_is_dirt_6d8c76_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_dirty'], name='inventory_p_is_dirt_806afc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['is_dirty'], name='inventory_p_is_dirt_f627d6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudit',
            index=models.Index(fields=['is_dirty'], name='inventory_s_is_dirt_a7fb60_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudititem',
            index=models.Index(fields=['audit'], name='inventory_s_audit_i_d58c81_idx'),
        ),
        migrations.AddIndex(
            model_name='stockaudititem',
            index=models.Index(fields=['is_dirty'], name='inventory_s_is_dirt_eb0629_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['is_dirty'], name='inventory_s_is_dirt_45cc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_dirty'], name='inventory_s_is_dirt_4bb11f_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['is_dirty'], name='inventory_w_is_dirt_6487e6_idx'),
        ),
    ]
