# Generated by Django 6.0 on 2026-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auditlog_is_dirty_inventoryitem_is_dirty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mraproductmapping',
            name='tax_calculation_method',
            field=models.CharField(choices=[('inclusive', 'Tax Inclusive (Price includes tax)'), ('exclusive', 'Tax Exclusive (Tax added to price)')], default='inclusive', help_text='How is tax calculated for this product? (Immutable once approved)', max_length=20),
        ),
    ]
