# Generated by Django 6.0 on 2026-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_mraproductmapping_tax_calculation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mraproductmapping',
            name='mra_tax_type',
            field=models.CharField(choices=[('standard', 'Standard Rated'), ('zero', 'Zero Rated (0%)'), ('exempt', 'Exempt')], help_text='MRA tax classification', max_length=20),
        ),
    ]
