# Generated by Django 4.2.11 on 2026-02-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_purchaseorderitem_session_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorderitem',
            name='inventory_p_session_idx',
        ),
    ]
