# Generated by Django 6.0 on 2026-02-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_purchaseorderitem_inventory_p_session_idx'),
        ('inventory', '0019_wasterecord_session_id'),
    ]

    operations = [
    ]
