# Generated by Django 6.0 on 2026-02-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_merge_20260219_0719'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wasterecord',
            name='inventory_w_session_idx',
        ),
    ]
