# Generated by Django 6.0 on 2026-02-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_mraproductmapping_branch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mraproductmapping',
            name='inventory_m_branch_approved_idx',
        ),
    ]
