# Generated by Codex for EIS stock receipt source tracking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_supplier_mra_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='eis_stock_receipt_source',
            field=models.CharField(
                choices=[
                    ('pos_goods_receiving', 'POS submits informal/manual purchase to EIS'),
                    ('supplier_sale', 'B2B stock transfer already posted in EIS'),
                ],
                default='pos_goods_receiving',
                help_text='Controls whether POS submits receive-stock to EIS or records only local batch details because a B2B EIS stock transfer already updated MRA stock.',
                max_length=32,
            ),
        ),
    ]
