# Generated by Codex for MRA EIS supplier detail parity.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_mraproductmapping_mra_levies'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
