# Generated by Django 6.0 on 2026-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_invoice_id_alter_planfeature_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enable_staff_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enable_stock_audits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enable_stock_transfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enable_take_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enable_tax_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enable_waste_management',
            field=models.BooleanField(default=False),
        ),
    ]
