# Generated by Django 6.0 on 2026-01-15 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_subscription_billing_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(db_index=True, help_text='Unique deposit identifier', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual (Admin)')], default='stripe', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='FeaturePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('pos', 'POS System'), ('inventory', 'Inventory Management'), ('invoicing', 'Invoicing'), ('online_menu', 'Online Menu'), ('online_ordering', 'Online Ordering'), ('delivery', 'Delivery Management'), ('kitchen', 'Kitchen Display System'), ('expense_management', 'Expense Management'), ('supplier_management', 'Supplier Management'), ('purchases', 'Purchase Orders'), ('low_stock_alerts', 'Low Stock Alerts'), ('expiry_alerts', 'Expiry Alerts'), ('customer_management', 'Customer Management'), ('reports', 'Reports'), ('analytics', 'Analytics'), ('take_orders', 'Take Orders'), ('staff_management', 'Staff Management'), ('waste_management', 'Waste Management'), ('stock_transfers', 'Stock Transfers'), ('stock_audits', 'Stock Audits'), ('tax_management', 'Tax Management')], max_length=50, unique=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily price for this feature', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('enabled_date', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.featurepricing')),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('base_daily', 'Base Daily Fee'), ('feature', 'Feature Usage'), ('transaction', 'Transaction'), ('storage', 'Storage'), ('api_call', 'API Call'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='last_billing_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='renewal_date',
            new_name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_period',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='max_branches',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='max_staff',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_days',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_start_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current account balance/credits', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_price_per_day',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Base daily subscription price', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_customer_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_expense_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_expiry_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_invoicing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_low_stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_online_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_online_ordering',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_purchases',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_staff_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_stock_audits',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_stock_transfers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_supplier_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_tax_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enable_waste_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_features', to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='usagecharge',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_charges', to='subscription.subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionfeature',
            unique_together={('subscription', 'feature')},
        ),
    ]
