# Generated by Django 6.0 on 2026-01-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_deposit_featurepricing_subscriptionfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('manual', 'Manual (Admin)')], default='stripe', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
