# Generated by Django 6.0 on 2026-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_deposit_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_proof',
            field=models.TextField(blank=True, help_text='Transaction ID, reference number, or payment confirmation details provided by user'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (admin use)'),
        ),
    ]
