# Generated by Django 4.2.11 on 2026-01-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_deposit_payment_proof_alter_deposit_notes'),
        ('subscription', '0010_subscription_free_trial_fields'),
    ]

    operations = [
    ]
