# Generated by Django 6.0 on 2026-02-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_merge_20260116_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enable_usage_limits',
            field=models.BooleanField(default=True, help_text='Enable usage limits for features'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_charge_date',
            field=models.DateTimeField(blank=True, help_text='Last date daily charges were applied', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='low_balance_notified',
            field=models.BooleanField(default=False, help_text='Whether low balance notification has been sent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='low_balance_notified_date',
            field=models.DateTimeField(blank=True, help_text='When low balance notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Alert when balance falls below this', max_digits=10),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_by', models.CharField(help_text='User who requested refund', max_length=255)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, help_text='Admin who approved refund', max_length=255)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('refund_method', models.CharField(choices=[('credit', 'Account Credit'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('original_method', 'Original Payment Method')], default='credit', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='subscription.deposit')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='subscription.subscription')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
    ]
