# Generated by Django 6.0 on 2026-02-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_remove_subscription_enable_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepricing',
            name='feature',
            field=models.CharField(choices=[('pos', 'POS System'), ('inventory', 'Inventory Management'), ('invoicing', 'Invoicing'), ('online_menu', 'Online Menu'), ('online_ordering', 'Online Ordering'), ('kitchen', 'Kitchen Display System'), ('expense_management', 'Expense Management'), ('supplier_management', 'Supplier Management'), ('purchases', 'Purchase Orders'), ('low_stock_alerts', 'Low Stock Alerts'), ('expiry_alerts', 'Expiry Alerts'), ('customer_management', 'Customer Management'), ('reports', 'Reports'), ('analytics', 'Analytics'), ('take_orders', 'Take Orders'), ('staff_management', 'Staff Management'), ('waste_management', 'Waste Management'), ('stock_transfers', 'Stock Transfers'), ('stock_audits', 'Stock Audits'), ('tax_management', 'Tax Management'), ('multi_branch', 'Multi-Branch Management')], max_length=50, unique=True),
        ),
    ]
