# Generated by Django 6.0 on 2026-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter')], default='Cashier', max_length=20),
        ),
    ]
