# Generated by Django 6.0 on 2026-02-13 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_branch_is_dirty_business_is_dirty_and_more'),
        ('staff', '0006_alter_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['business', 'is_active'], name='staff_staff_busines_0b960e_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_dirty'], name='staff_staff_is_dirt_976fc3_idx'),
        ),
    ]
