# Generated by Django 6.0 on 2026-01-15 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('pos', 'POS System'), ('inventory', 'Inventory Management'), ('invoicing', 'Invoicing'), ('online_menu', 'Online Menu'), ('online_ordering', 'Online Ordering'), ('delivery', 'Delivery Management'), ('kitchen', 'Kitchen Display System'), ('expense_management', 'Expense Management'), ('supplier_management', 'Supplier Management'), ('purchases', 'Purchase Orders'), ('low_stock_alerts', 'Low Stock Alerts'), ('expiry_alerts', 'Expiry Alerts'), ('customer_management', 'Customer Management'), ('reports', 'Reports'), ('analytics', 'Analytics'), ('take_orders', 'Take Orders'), ('staff_management', 'Staff Management'), ('waste_management', 'Waste Management'), ('stock_transfers', 'Stock Transfers'), ('stock_audits', 'Stock Audits'), ('tax_management', 'Tax Management')], help_text='Feature identifier', max_length=50, unique=True)),
                ('default_price_per_day', models.DecimalField(decimal_places=2, default=0.0, help_text='Default daily price for this feature', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_price_per_day_mwk', models.DecimalField(decimal_places=2, default=0.0, help_text='Default daily price (MWK) for this feature for Malawi', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_price_per_day_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Default daily price (USD) for this feature for International', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Feature description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is available')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether this is a premium feature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Feature Pricing Configurations',
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], help_text='Payment gateway identifier', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this payment gateway is enabled')),
                ('api_key', models.CharField(blank=True, help_text='API key for the payment gateway', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret for the payment gateway', max_length=500)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for payment notifications')),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook secret for verification', max_length=500)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_transaction_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum transaction amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Gateway Configurations',
                'ordering': ['gateway'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_subscription_price_per_day', models.DecimalField(decimal_places=2, default=5.0, help_text='Default base subscription price per day', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_subscription_price_per_day_mwk', models.DecimalField(decimal_places=2, default=5000.0, help_text='Base subscription price per day for Malawi (MWK)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_subscription_price_per_day_usd', models.DecimalField(decimal_places=2, default=5.0, help_text='Base subscription price per day for International (USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_currency', models.CharField(default='MWK', help_text='Default currency code (ISO 4217)', max_length=3)),
                ('malawi_currency_code', models.CharField(default='MWK', help_text='Currency code for Malawian businesses', max_length=3)),
                ('international_currency_code', models.CharField(default='USD', help_text='Currency code for international businesses', max_length=3)),
                ('trial_days', models.IntegerField(default=14, help_text='Number of days for free trial', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('enable_feature_pricing', models.BooleanField(default=True, help_text='Enable per-feature pricing')),
                ('invoice_due_days', models.IntegerField(default=7, help_text='Number of days until invoice is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('minimum_deposit_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum deposit amount allowed', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_deposit_amount', models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum deposit amount allowed', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_balance_threshold_days', models.IntegerField(default=7, help_text='Days of service remaining before low balance alert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('system_name', models.CharField(default='Handy POS', help_text='System/Company name', max_length=255)),
                ('system_email', models.EmailField(default='support@handypos.com', help_text='System support email', max_length=254)),
                ('system_phone', models.CharField(blank=True, help_text='System support phone number', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
