# Generated by Django 6.0 on 2026-01-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('MWK', 'Malawi Kwacha'), ('USD', 'US Dollar')], help_text='Currency for this bank account', max_length=3, unique=True)),
                ('account_holder', models.CharField(help_text='Bank account holder name', max_length=255)),
                ('bank_name', models.CharField(help_text='Bank name', max_length=255)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=255)),
                ('routing_number', models.CharField(blank=True, help_text='Bank routing number (optional)', max_length=255)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT code (optional)', max_length=20)),
                ('iban', models.CharField(blank=True, help_text='IBAN (optional)', max_length=50)),
                ('instructions', models.TextField(blank=True, help_text='Additional transfer instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Transfer Configurations',
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Mobile money provider name (e.g., Airtel Money, TNM Mpamba)', max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this mobile money provider is enabled')),
                ('account_number', models.CharField(help_text='Mobile money account number or phone number', max_length=255)),
                ('account_name', models.CharField(blank=True, help_text='Account holder name', max_length=255)),
                ('instructions', models.TextField(blank=True, help_text='Payment instructions for customers')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Money Configurations',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('MWK', 'Malawi Kwacha'), ('USD', 'US Dollar')], help_text='Currency for this payment method', max_length=3)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], help_text='Payment method type', max_length=50)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this payment method is enabled for this currency')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Method Configurations',
                'ordering': ['currency', 'display_order'],
                'unique_together': {('currency', 'payment_method')},
            },
        ),
    ]
