# Generated by Django 6.0 on 2026-02-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_banktransferconfig_mobilemoneyconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransferconfig',
            options={'ordering': ['currency'], 'verbose_name_plural': 'Bank Transfer Configurations'},
        ),
    ]
