# Generated by Django 6.0 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_branch_id_alter_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(default='Malawi', help_text='Country where the business is located', max_length=100),
        ),
    ]
