# Generated by Django 6.0 on 2026-01-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_invoice_related_order_id'),
        ('business', '0008_business_country'),
    ]

    operations = [
    ]
