# Generated by Django 6.0 on 2026-01-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_merge_20260117_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Utilities', 'Utilities'), ('Rent', 'Rent'), ('Salaries', 'Salaries'), ('Supplies', 'Supplies'), ('Marketing', 'Marketing'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, help_text='User who approved/rejected the expense', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of approval/rejection', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status for invoice review', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.CharField(blank=True, help_text='User who approved/rejected the invoice', max_length=255),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'approval_status'], name='business_in_busines_d6ef62_idx'),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='business.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='business.business'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'status'], name='business_ex_busines_634573_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'created_at'], name='business_ex_busines_0dac8b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='business_ex_categor_6edbc3_idx'),
        ),
    ]
