# Generated by Django 6.0 on 2026-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_taxrate_enhanced_fields'),
        ('business', '0011_add_slugs'),
    ]

    operations = [
    ]
