# Generated by Django 6.0 on 2026-01-24 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_merge_0008_taxrate_enhanced_fields_0011_add_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxrate',
            name='one_active_default_tax_per_business',
        ),
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('business',), name='one_active_default_tax_per_business'),
        ),
    ]
