# Generated by Django 6.0 on 2026-02-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_taxrate_one_active_default_tax_per_business_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mra_product_code', models.CharField(blank=True, help_text='MRA product code', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='branch',
            name='mra_branch_code',
            field=models.CharField(blank=True, help_text='MRA-assigned branch code for tax reporting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='mra_device_location',
            field=models.CharField(blank=True, help_text='Physical location description for MRA records', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='mra_enrolled',
            field=models.BooleanField(default=False, help_text='Is this business enrolled in MRA EIS?'),
        ),
        migrations.AddField(
            model_name='business',
            name='mra_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='When was this business enrolled in MRA EIS?', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='mra_taxpayer_type',
            field=models.CharField(choices=[('VAT', 'VAT Registered'), ('NON_VAT', 'Non VAT Registered')], default='NON_VAT', help_text='MRA taxpayer classification', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='tin',
            field=models.CharField(blank=True, help_text='Taxpayer Identification Number (MRA) - MUST be unique', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Is this business VAT registered?'),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_registration_number',
            field=models.CharField(blank=True, help_text='VAT Registration Number from MRA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='block_sales_if_eis_down',
            field=models.BooleanField(default=True, help_text='Block POS sales if EIS is unavailable (MRA requirement)'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='eis_environment',
            field=models.CharField(choices=[('TEST', 'Test/Sandbox'), ('PROD', 'Production')], default='TEST', help_text='MRA EIS environment (sandbox or production)', max_length=20),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='enable_eis',
            field=models.BooleanField(default=False, help_text='Enable MRA EIS integration for this business'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_tin',
            field=models.CharField(blank=True, help_text='Customer TIN (for B2B invoices)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_registered',
            field=models.BooleanField(default=False, help_text='Is customer VAT registered?'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Is this invoice locked? (read-only after payment/submission)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mra_invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number assigned by MRA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mra_qr_code',
            field=models.TextField(blank=True, help_text='QR code data from MRA', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mra_receipt_signature',
            field=models.TextField(blank=True, help_text='Cryptographic signature from MRA', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mra_status',
            field=models.CharField(choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted to MRA'), ('ACCEPTED', 'Accepted by MRA'), ('REJECTED', 'Rejected by MRA')], default='PENDING', help_text='MRA submission status', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mra_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When was this invoice submitted to MRA?', null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='locked',
            field=models.BooleanField(default=False, help_text='Is this tax rate locked? (cannot be edited after use)'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='mra_tax_code',
            field=models.CharField(blank=True, help_text='MRA tax code for this rate', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['business', 'is_active'], name='business_br_busines_b64ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['mra_branch_code'], name='business_br_mra_bra_168744_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['tin'], name='business_bu_tin_ebf2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['mra_enrolled'], name='business_bu_mra_enr_0006f6_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'vat_registered'], name='business_cu_busines_dddff6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['mra_status'], name='business_in_mra_sta_11b506_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_locked'], name='business_in_is_lock_2e4b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['business', 'is_active'], name='business_ta_busines_b920b4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['locked'], name='business_ta_locked_9c4b30_idx'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.invoice'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice'], name='business_in_invoice_0446b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['mra_product_code'], name='business_in_mra_pro_38c420_idx'),
        ),
    ]
