# Generated by Django 6.0 on 2026-02-13 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_invoiceline_remove_invoice_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_dirty',
            field=models.BooleanField(default=True, help_text='Marks record as dirty (needs syncing). Set to False after successful sync.'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_dirty'], name='business_br_is_dirt_dc5649_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_dirty'], name='business_bu_is_dirt_d1cb46_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_dirty'], name='business_cu_is_dirt_d86dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_dirty'], name='business_ex_is_dirt_85b85a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_dirty'], name='business_in_is_dirt_0618a3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['is_dirty'], name='business_in_is_dirt_da2e43_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['is_dirty'], name='business_ta_is_dirt_c1b32a_idx'),
        ),
    ]
